### ISSUE TITLE
Sensor disappeared

### ISSUE THREAD

**Issue by zbeez** [amaximus/water_quality_fvm#2]
Hello amaximus,

just realized that the sensor of the water quality is gone missing. Maybe because the site https://www.vizmuvek.hu/hu/fovarosi-vizmuvek/lakossagi-ugyfelek/altalanos_informaciok/vizminoseg_vizkemenyseg has a 404 Error?
Could you look into that if you have the time?

Thank you!!!

**Comment by KixMan28** [comment]
Same error on my side.

**Comment by amaximus** [comment]
Newest release (0.1.0) updates the changed URL.

Please update your custom integration and get back to me with results.

**Comment by KixMan28** [comment]
It works, thank you for the quick fix.

**Comment by zbeez** [comment]
Indeed! It works again. Thank you very much for the update! 
Wishing you nice Christmas celebrations!
